MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
 - "10.15"                # [osx and x86_64]

MACOSX_SDK_VERSION:        # [osx and x86_64]
 - "10.15"                # [osx and x86_64]

CFLAGS:
 - "-mmacosx-version-min=10.15"  # [osx and x86_64]
CXXFLAGS:
 - "-mmacosx-version-min=10.15"  # [osx and x86_64]
LDFLAGS:
 - "-mmacosx-version-min=10.15"  # [osx and x86_64]
