os:
  - osx
  - linux
language: generic
sudo: required

services:
  - docker

before_install:
    - set -e
    - |
      if [ "$TRAVIS_OS_NAME" == "linux" ]
      then
        rm -rf /home/travis/perl5/ /home/travis/.phpenv /home/travis/gopath /home/travis/otp
        rm -rf /home/travis/.gimme/ /home/travis/.rvm /home/travis/.nvm
      fi

install: scripts/travis-setup.sh

script: scripts/travis-run.sh

env:
  global:
    - SUBDAGS=1
    - BIOCONDA_UTILS_TAG=six
    - BIOCONDA_UTILS_BUILD_ARGS="--loglevel=info"
    - BIOCONDA_UTILS_LINT_ARGS=
    - MINICONDA_VER="4.2.12"
  matrix:
    - SUBDAG=0

matrix:
  fast_finish: true
