os:
- linux
- osx
language: python - "3.5"
sudo: required
services:
- docker
install: ./travis-setup.sh
before_script:
- export PATH=/opt/involucro:/anaconda/bin:$PATH
script: ./travis-run.sh
env:
  global:
  - secure: lg+4gQIIVs7hII4v2Jx9n8dt3zyX9dlAqN8/DNCbHk4u/iJPSVHIk5IhBChjhbU8Eg4Zg2jL2kwTHg2t0W6auZZTWxfznH4enVQP2fRzjHsKBib/ksr41yeI0Mjsybivf5sdjjR8ewQ0ZwJpMF7RFkir38uJAIyDamm9tsVO71KHLLCkSnQ7lxnJpZfUyL4zCW6lo7UZGXOlFi1ZPdWIpAiY1ge1nfsaOjuUn5G5uKcdWMnrAm9E7MVxIz+vyP4iJMemoCotr0FrWfj4SjCYQURIDPHBpzdorBu2+JaE+9pJR3kt0EgGAuZBP41anKn0806Csh7Ar1bPfp7ORum32Ml7yMaqFSAT8I5F5n35olR72QppiHoVCNmU0zPCGrAWhNBaBs/hMjwm8KFF6iAC00N8RMGYKNH6oF7psDRyGSJjJjeqwvsuXJCkT5zyvvg6fraLfzhmeGY2OmYe4hrNkAMco+dJOV0bfyR6rnerFOdu+9i/ytRuwcMxcClZEdklSlsFz/+MzJubL9va+Y4I7RHIRyUyu69BwgiL0Af7Q50cHEl1iSCedyVYiQRQgJGDNI9UAm2cc4Wibj8N6UMkLh76ApUs/zENnPJcopzbH/r5epIpu1y826nEXtfrm3NM0Rg6XDA8rcqzEsGI/JQGGJr+l4LgUy6lPCAqISJWazs=
  - ENCRYPTION_LABEL=4abdd40b7eaf
  - MINICONDA_VER="4.2.12"

matrix:
  fast_finish: true
  - BIOCONDA_UTILS_TEST_TYPE=pytest
  - BIOCONDA_UTILS_TEST_TYPE=docs

branches:
  only:
    - master
