language: generic
sudo: required

services:
  - docker

osx_image: xcode7.3

before_install:
    - set -e
    - |
      if [ "$TRAVIS_OS_NAME" == "linux" ]
      then
        rm -rf /home/travis/perl5/ /home/travis/.phpenv /home/travis/gopath /home/travis/otp
        rm -rf /home/travis/.gimme/ /home/travis/.rvm /home/travis/.nvm
      fi

install: scripts/travis-setup.sh

jobs:
  include:
    # in forks, master and bulk, we run osx and linux in parallel on each push
    - stage: Linux+macOS
      if: (type = push) AND ((branch IN (master, bulk)) OR (repo != bioconda/bioconda-recipes))
      os: linux
      script: scripts/travis-run.sh
    - os: osx
      if: (type = push) AND ((branch IN (master, bulk)) OR (repo != bioconda/bioconda-recipes))
      script: scripts/travis-run.sh
    # in pull requests, we first run linux and only if that succeeds, we run osx
    - stage: Linux
      if: type = pull_request
      os: linux
      script: scripts/travis-run.sh
    - stage: macOS
      if: type = pull_request
      os: osx
      script: scripts/travis-run.sh

env:
  global:
    - SUBDAGS=1
    - BIOCONDA_UTILS_TAG=master
    - BIOCONDA_UTILS_BUILD_ARGS="--loglevel=info"
    - BIOCONDA_UTILS_LINT_ARGS=
    - MINICONDA_VER="4.3.21"
  matrix:
    - SUBDAG=0

matrix:
  fast_finish: true
