env_matrix: "scripts/env_matrix.yml"
blacklists:
    - "sorted-r-blacklist"

docker_image: "continuumio/conda_builder_linux:5.11-5.2-0-1"
channels:
    - anaconda
    - conda-forge
    - r
    - bioconda
docker_client_version: '1.20'
