
blacklists:
    - "build-fail-blacklist"

# Channels ordered from highest to lowest priority. This should match the order
# of .condarc, but when adding channels using conda config --add, they should
# be added in reverse (from low to high priority).
channels:
    - conda-forge
    - bioconda
    - defaults
