env_matrix: "scripts/env_matrix.yml"
blacklists:
    - "r-blacklist"

docker_image: "continuumio/conda_builder_linux:5.11-5.2-0-1"
channels:
    - default
    - r
    - bioconda
    # - conda-forge
docker_client_version: '1.20'
