env_matrix: "scripts/env_matrix.yml"
blacklists:
    - "sorted-r-blacklist"
    - "build-fail-blacklist"

docker_image: "condaforge/linux-anvil"
channels:
    - conda-forge
    - defaults
    - r
    - bioconda
docker_client_version: '1.20'
