env_matrix: "scripts/env_matrix.yml"
blacklists:
    - "sorted-r-blacklist"
    - "build-fail-blacklist"
    - "boost-1.61-migration-blacklist"
    - "perl-unable-to-find-blacklist"

docker_image: "condaforge/linux-anvil"

# Channels ordered from highest to lowest priority. This should match the order
# of .condarc, but when adding channels using conda config --add, they should
# be added in reverse (from low to high priority).
channels:
    - bioconda
    - r
    - defaults
    - conda-forge
docker_client_version: '1.20'
