env_matrix: scripts/env_matrix.yml
#
# blacklists:
#   - r-blacklist
# index_dirs:
#   - /anaconda/conda-bld/linux-64
#   - /anaconda/conda-bld/osx-64
# setup:
#   - pip install git+https://github.com/bioconda/conda-build.git@reintroduce-skip-existing
