zip_keys:
  - python
  - python_impl
  - numpy

python:
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313

python_impl:
  - cpython
  - cpython
  - cpython
  - cpython

numpy:
  - 1.26
  - 1.26
  - 1.26
  - 2.1
