MACOSX_DEPLOYMENT_TARGET: '10.9'
VERBOSE_AT: V=1
VERBOSE_CM: VERBOSE=1
c_compiler: gcc
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
extend_keys:
- pin_run_as_build
- ignore_version
- ignore_build_only_deps
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
libcurl: '7.62'
libopenblas: 0.3.3
lua: '5'
macos_machine: x86_64-apple-darwin13.4.0
macos_min_version: '10.9'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.7'
r_base: 3.6.1
rstudio_variant: ''
target_platform: linux-64
