# recipes/decenttree/conda_build_config.yaml
c_compiler:
  - gcc      # [linux]
  - clang    # [osx]
cxx_compiler:
  - gxx      # [linux]
  - clangxx  # [osx]
c_compiler_version:
  - 11       # [linux]
cxx_compiler_version:
  - 11       # [linux]
