c_compiler:             # [osx]
  - gcc                 # [osx]
c_compiler_version:     # [osx]
  - 15                  # [osx]
cxx_compiler:           # [osx]
  - gxx                 # [osx]
cxx_compiler_version:   # [osx]
  - 15                  # [osx]
