CI: azure
c_compiler: gcc
c_compiler_version: '9'
cdt_name: cos6
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '9'
docker_image: quay.io/condaforge/linux-anvil-comp7
extend_keys:
- extend_keys
- ignore_version
- ignore_build_only_deps
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.11'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.8'
r_base: '3.5'
target_platform: linux-64
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
