c_compiler:            # [osx]
  - clang              # [osx]
c_compiler_version:    # [osx]
  - 9                  # [osx]
cxx_compiler:          # [osx]
  - clangxx            # [osx]
cxx_compiler_version:  # [osx]
  - 9                  # [osx]
