zip_keys:
  - python
  - python_impl
  - numpy

python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cpython

python_impl:
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython

numpy:
  - 2.*
  - 2.*
  - 2.*
  - 2.*
