# Additional bioconda-specific pinnings to use in addition to those specified
# in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

# clear hard-coded default value for CONDA_BUILD_SYSROOT
CONDA_BUILD_SYSROOT:
  - ''

pin_run_as_build:
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
  r-base:
    max_pin: x.x
    min_pin: x.x

htslib:
  - 1.9
bamtools:
  - 2.5.1
r_base:
  - 3.6
