zip_keys:
  - python
  - python_impl
  - numpy

python:
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
  # - 3.14.* *_cp314

python_impl:
  - cpython
  - cpython
  - cpython
  # - cpython

numpy:
  - 1.26
  - 1.26
  - 2.1
  # - 2.2

channel_sources:
  - conda-forge,bioconda

channel_targets:
  - bioconda main
