package:
  name: bioconda-utils
  version: 1.0.999

source:
  git_url: https://github.com/bioconda/bioconda-utils.git
  git_tag: 'master'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - bioconda-utils = bioconda_utils.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - aiofiles 0.8.*
    - aioftp 0.12.*
    - aiohttp 3.8.*
    - aiohttp-jinja2
    - aiohttp-security
    - aiohttp-session
    - alabaster 0.7.*
    - anaconda-client 1.6.*
    - argh 0.26.*
    - backoff 1.6.*
    - beautifulsoup4 4.6.*
    - boa 0.9.*
    - boltons 18.*
    - cachetools 3.0.*
    - celery
    - colorlog 3.1.*
    - conda 4.12.0
    - conda-build >=3.21.8
    - conda-forge-ci-setup
    - conda-forge-pinning 2022.02.18.13.24.38
    - conda-verify 3.1.*
    - docutils
    - galaxy-lib >=18.9.1
    - gidgethub 3.0.*
    - git >=2
    - gitpython >=3.0.8,3.0.*
    - graphviz
    - involucro 1.1.*
    - jinja2 >2.10.1,<3
    - jsonschema 2.6.*
    - libblas * *openblas
    - markdown
    - markupsafe <2.1
    - networkx 2.*
    - numpy 1.19.*
    - pandas 0.23.*
    - pyaml 17.12.*
    - pyjwt >=2.4.0
    - python >=3.7
    - regex 2018.08.29
    - requests 2.22.*
    - ruamel_yaml 0.15.*
    - simplejson
    - skopeo 0.1.35
    - sphinx >=4.1
    - sphinx-autodoc-typehints
    - tqdm >=4.26

test:
  imports:
    - bioconda_utils
  commands:
    - bioconda-utils --help
    - bioconda-utils lint --help
    - bioconda-utils build --help
    - >
      CONDA_AGGRESSIVE_UPDATE_PACKAGES=
      CONDA_AUTO_UPDATE_CONDA=0
      "${PREFIX}/bin/conda" install --prefix="${PREFIX}" --dry-run --satisfied-skip-solve
      --file="$( python -c
      'from os.path import dirname, join; import bioconda_utils; print(join(dirname(bioconda_utils.__file__), "bioconda_utils-requirements.txt"))'
      )"
      2>&1 > OUT
    - cat OUT
    - grep --version
    - grep OUT -q -F 'All requested packages already installed.'

about:
  home: http://bioconda.github.io/build-system.html
  license: MIT
  license_family: MIT
  summary: Utilities for building and managing bioconda recipes.
  dev_url: https://github.com/bioconda/bioconda-utils
