name: Test
on: [push]
jobs:
  test-linux:
    name: Shorter linux tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dpryan79/github-actions/bioconda_utils_setup_conda/@master
    - name: Install bioconda-utils
      run: |
        python setup.py install
    - name: Build docker container
      run: |
        docker build -t bioconda-utils-build-env:latest ./
        docker history bioconda-utils-build-env:latest
        docker run --rm -t bioconda-utils-build-env:latest sh -lec 'type -t conda && conda info -a && conda list'
    - name: Run shorter tests
      run: |
        if git diff --name-only origin/master...HEAD | grep -vE ^docs; then
            py.test --durations=0 test/ -v --tb=native -m 'not long_running'
        else
            echo "Skipping pytest - only docs modified"
        fi
